name: Ant CI/CD

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Ant đã cài sẵn trên GitHub runner, song bảo đảm phiên bản mới
      - name: Ensure Ant is installed
        run: |
          sudo apt-get update
          sudo apt-get install -y ant

      - name: Download dependencies
        run: ant download-dependencies

      - name: Build WAR with Ant
        run: ant -noinput war

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: Storee-WAR
          path: dist/Storee.war